# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: julio@jcorpus.me
copyright_name: jcorpus
description: "Blog personal..."
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://jcorpus.me"
twitter_username: jsuproc
github_username:  jcorpus
facebook_username:  jsuproc
email_username:  julio@jcorpus.me

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
