# Site settings
title: Blog jCorpus
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: jCorpus Blog Made with Github
description: "Blog de noticias y más."
baseurl: ""
url: "jcorpus.github.io"
twitter_username: jsuproc
github_username:  jcorpus
facebook_username:  jsuproc
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id:UA-48091222-6

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
